// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_specializing = "CgkIr_aWn6gCEAIQCw"; // <GPGSID>
        public const string achievement_creating_a_medium_team = "CgkIr_aWn6gCEAIQDQ"; // <GPGSID>
        public const string achievement_creating_a_big_team = "CgkIr_aWn6gCEAIQDg"; // <GPGSID>
        public const string leaderboard_total_money = "CgkIr_aWn6gCEAIQAQ"; // <GPGSID>
        public const string achievement_goodbye_cute_pig = "CgkIr_aWn6gCEAIQHg"; // <GPGSID>
        public const string achievement_super_big_multiverse = "CgkIr_aWn6gCEAIQHA"; // <GPGSID>
        public const string achievement_starting_a_company = "CgkIr_aWn6gCEAIQEQ"; // <GPGSID>
        public const string achievement_stating_the_universe = "CgkIr_aWn6gCEAIQGA"; // <GPGSID>
        public const string achievement_why_so_big_4 = "CgkIr_aWn6gCEAIQHQ"; // <GPGSID>
        public const string achievement_why_so_big_3 = "CgkIr_aWn6gCEAIQFw"; // <GPGSID>
        public const string achievement_spinninggg = "CgkIr_aWn6gCEAIQLA"; // <GPGSID>
        public const string achievement_why_so_big_2 = "CgkIr_aWn6gCEAIQEA"; // <GPGSID>
        public const string leaderboard_money_per_second = "CgkIr_aWn6gCEAIQAg"; // <GPGSID>
        public const string achievement_super_big_company = "CgkIr_aWn6gCEAIQFQ"; // <GPGSID>
        public const string achievement_big_multiverse = "CgkIr_aWn6gCEAIQGw"; // <GPGSID>
        public const string achievement_make_me_rich = "CgkIr_aWn6gCEAIQIw"; // <GPGSID>
        public const string achievement_more_drop_more_money_2 = "CgkIr_aWn6gCEAIQKA"; // <GPGSID>
        public const string achievement_spinninggggggg = "CgkIr_aWn6gCEAIQLg"; // <GPGSID>
        public const string achievement_golddd = "CgkIr_aWn6gCEAIQJQ"; // <GPGSID>
        public const string achievement_a_nice_pocket = "CgkIr_aWn6gCEAIQHw"; // <GPGSID>
        public const string achievement_starting_a_farm = "CgkIr_aWn6gCEAIQAw"; // <GPGSID>
        public const string achievement_upgrade_the_incoming = "CgkIr_aWn6gCEAIQJA"; // <GPGSID>
        public const string achievement_medium_multiverse = "CgkIr_aWn6gCEAIQGg"; // <GPGSID>
        public const string achievement_upgrade_the_space = "CgkIr_aWn6gCEAIQIQ"; // <GPGSID>
        public const string achievement_multinational_company = "CgkIr_aWn6gCEAIQFg"; // <GPGSID>
        public const string achievement_what_has_at_the_end_of_the_rainbow = "CgkIr_aWn6gCEAIQIA"; // <GPGSID>
        public const string achievement_medium_company = "CgkIr_aWn6gCEAIQEw"; // <GPGSID>
        public const string achievement_creating_a_small_team = "CgkIr_aWn6gCEAIQDA"; // <GPGSID>
        public const string achievement_creating_a_very_big_team = "CgkIr_aWn6gCEAIQDw"; // <GPGSID>
        public const string achievement_unnecessarily_big_farm = "CgkIr_aWn6gCEAIQCA"; // <GPGSID>
        public const string achievement_small_multiverse = "CgkIr_aWn6gCEAIQGQ"; // <GPGSID>
        public const string achievement_i_need_that_much_money_2 = "CgkIr_aWn6gCEAIQKg"; // <GPGSID>
        public const string achievement_beginning_of_career = "CgkIr_aWn6gCEAIQCg"; // <GPGSID>
        public const string achievement_little_farm = "CgkIr_aWn6gCEAIQBA"; // <GPGSID>
        public const string achievement_super_big_farm = "CgkIr_aWn6gCEAIQBw"; // <GPGSID>
        public const string achievement_more_drop_more_money = "CgkIr_aWn6gCEAIQJw"; // <GPGSID>
        public const string achievement_big_farm = "CgkIr_aWn6gCEAIQBg"; // <GPGSID>
        public const string achievement_why_so_big = "CgkIr_aWn6gCEAIQCQ"; // <GPGSID>
        public const string achievement_i_need_that_much_money = "CgkIr_aWn6gCEAIQKQ"; // <GPGSID>
        public const string achievement_average_farm = "CgkIr_aWn6gCEAIQBQ"; // <GPGSID>
        public const string achievement_aaaaaaaaa = "CgkIr_aWn6gCEAIQJg"; // <GPGSID>
        public const string achievement_big_company = "CgkIr_aWn6gCEAIQFA"; // <GPGSID>
        public const string achievement_spinning = "CgkIr_aWn6gCEAIQKw"; // <GPGSID>
        public const string achievement_wow = "CgkIr_aWn6gCEAIQIg"; // <GPGSID>
        public const string achievement_spinninggggg = "CgkIr_aWn6gCEAIQLQ"; // <GPGSID>
        public const string achievement_small_company = "CgkIr_aWn6gCEAIQEg"; // <GPGSID>

}

